apiVersion: v1
kind: ConfigMap
metadata:
  name: react-frontend-config
  namespace: default
data:
  VITE_API_GATEWAY_URL: "http://api-gateway:8000"
  VITE_SERVICE_NAME: "react-frontend"
  VITE_SERVICE_VERSION: "1.0.0"
  VITE_ENV: "production"
  VITE_ENABLE_SERVICE_DISCOVERY: "false"
  VITE_ENABLE_MONITORING: "true"
  VITE_ENABLE_LOGGING: "true"
  VITE_API_TIMEOUT: "30000"
  VITE_LOG_LEVEL: "info"
